name: Build ReXGlue GUI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Накатываем актуальный .NET SDK (поддерживающий .slnx)
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # или '9.x', если проект обновлен

    # Публикуем (собираем) проект сразу в одну фиксированную папку output
    - name: dotnet publish
      run: dotnet publish "ReXGlue GUI.slnx" -c Release -o ./output /p:PublishSingleFile=true /p:PublishReadyToRun=true

    # Забираем ВСЁ содержимое папки output. Экзешник точно будет там.
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ReXGlue-GUI-Windows-Release
        path: ./output/
